class Samples {
  static const samples = [
    "for time\r\n1500 mt run\r\n21 sumo deadlift high-pull\r\n10 burpee\r\n15 push press\r\n300 mt run\r\n21 kettlebell swing\r\n15 deadlift",
    "9 rounds for time\r\n10 push-up\r\n15 double under",
    "for time\r\n400 mt run\r\n50 kettlebell swing\r\n10 pull-up\r\n200 mt row\r\n12 burpee over the bar\r\n10 pull-up\r\n50 mt sprint",
    "2 rounds for time\r\n30 thruster\r\n15 pull-up",
    "2 rounds for time\r\n800 mt run\r\n21 thruster\r\n40 sit-up\r\n400 mt run\r\n20 thruster\r\n20 pull-up",
    "for time\r\n2000 mt run\r\n100 sit-up\r\n100 air squat",
    "5 rounds for time\r\n22 sit-up\r\n4 thruster\r\n10 burpee box jump over\r\n15 toes-to-bar",
    "5 rounds for time 15 minutes\r\n15 power snatch\r\n800 mt run",
    "2 rounds for time\r\n400 mt run\r\n20 mt handstand walk\r\n25 one-legged squat",
    "5 rounds\r\n10 push press\r\n25 squat",
    "5 rounds for time\r\n400 mt run\r\n21 kettlebell swing\r\n9 burpee",
    "6 rounds for time\r\n8 deadlift\r\n8 box jump\r\n3 clean\r\n10 sit-up\r\n10 toes-to-bar\r\n10 push-up",
    "5 rounds\r\n15 sit-up\r\n200 mt run\r\n10 wall-ball\r\n10 one legged squat\r\n15 pull-up",
    "8 rounds for time\r\n4 strict pull-up\r\n4 ring dip\r\n8 toes-to-bar\r\n10 dumbbell hang power clean\r\n6 thruster",
    "3 rounds for time\r\n400 mt run\r\n15 ground to overhead\r\n10 burpee over the bar\r\n260 mt run",
    "5 rounds for time\r\n15 box jump\r\n21 jumping lunges\r\n15 pull-up\r\n200 mt run",
    "5 rounds for time\r\n400 mt run\r\n21 kettlebell swing\r\n20 pull-up",
    "5 rounds for time\r\n200 mt sprint\r\n60 seconds air squat",
    "for time\r\n1000 mt row\r\n21 thruster\r\n30 pull-up",
    "for time\r\n50 box jump\r\n30 wall-ball\r\n30 knees to elbow\r\n20 squat clean\r\n30 sit-up",
    "for time\r\n10-9-8-7-6-5-4-3-2-1 reps of\r\nwall-ball\r\n* 300 mt row after every round",
    "3 rounds for time\r\n50 air squat\r\n36 sit-up\r\n30 back extension\r\n30 sit-up\r\n30 push-up\r\n400 mt run",
    "for time\r\n50-40-30-20-10 reps of\r\ndumbbell ground to overhead\r\nburpee",
    "5 rounds for time\r\n10 pull-up\r\n12 ring dip\r\n20 sit-up",
    "5 rounds for time\r\ncash in: 800 mt run\r\n21 box jump\r\n10 bench press\r\n10 push press",
    "amrap 10 minutes\r\n10 dumbbell push press\r\n12 box jump\r\n9 pull-up",
    "3 rounds for time\r\n21 deadlift\r\n24 knees to elbow\r\n20 broad jump\r\n22 mountain climber\r\n12 hang snatch\r\n12 box jump over",
    "5 rounds for time\r\n100 mt sprint\r\n400 mt row",
    "3 rounds\r\n25 wall-ball\r\n15 box jump over\r\n25 cal row",
    "3 rounds for time\r\n9 power snatch\r\n15 thruster\r\n21 cal row\r\n10 power clean & push jerk\r\n15 kettlebell swing",
    "3 rounds for time\r\n21 thruster\r\n21 sumo deadlift high pull\r\n21 knees to elbow\r\n30 double under\r\n15 knees to elbow",
    "2 rounds for time\r\n2 muscle-up\r\n10 thruster\r\n20 box jump",
    "12 rounds\r\ncash in: 40 box jump over\r\n20 wall-ball\r\n12 pull-up",
    "5 rounds for time\r\n250 mt row\r\n15 air squat",
    "3 rounds for time\r\n10 power clean\r\n200 mt run\r\n21 knees to elbow\r\n13 clean & jerk\r\n25 cal row\r\n30 thruster\r\n9 rope climb",
    "3 rounds for time\r\n50 mt walking lunge\r\n10 chest-to-bar pull-up\r\n15 kettlebell swing",
    "for time\r\n50 one-legged squat\r\n40 pull-up\r\n30 push-up\r\n30 squat\r\n20 box jump over",
    "for time\r\n21-15-9 reps of\r\nkettlebell swing\r\nbox jump",
    "amrap 12 minutes\r\n9 deadlift\r\n3 bear complex\r\n15 medicine ball clean",
    "for time\r\n21-15-9 reps of\r\nthruster\r\nsumo deadlift high pull\r\nsit-up\r\nsquat clean\r\n* 30 seconds rest",
    "3 rounds for time\r\n25 wall-ball\r\n400 mt run",
    "team of 2 complete amrap 40 minutes\r\n40 kettlebell swing\r\n30 cal row\r\n30 bench press",
    "5 rounds for time\r\n20 box jump over\r\n20 front squat\r\n20 knees to elbow",
    "amrap 15 minutes\r\n10 power snatch\r\n15 wall-ball",
    "for time\r\n30-20-10 reps of\r\npush press\r\n* 40 burpee after every round",
    "for time\r\n21-18-15-12-9 reps of\r\ndeadlift\r\nhandstand push-up",
    "for time\r\n50 push-up\r\n100 sit-up\r\n100 squat",
    "8 rounds for time\r\n12 pull-up\r\n10 thruster",
    "5 rounds for time 15 minutes\r\n5 handstand push-up\r\n10 one legged squat\r\n15 pull-up",
    "5 rounds\r\nmax cal row for 3 minutes\r\nmax rep medicine ball clean for 1 minute\r\n3 minutes rest\r\nmax rep sumo deadlift high pull for 60 seconds\r\n10 seconds rest",
    "4 mounds for time\r\n10 push press\r\n10 dumbbell ground to overhead\r\n20 burpee",
    "for time\r\n21-18-15-12-9-6-3 reps of\r\nclean & jerk\r\nbox jump",
    "3 rounds for time\r\n40 double under\r\n8 rope climb\r\n20 push-up",
    "for time 15 minutes\r\n3,6,9,12,15... reps of\r\nclean\r\nring dip",
    "for time\r\n21 pull-up\r\n30 sit-up\r\n2 muscle-up\r\n15 left-legged pistol\r\n55 sit-up\r\n9 sumo deadlift high pull\r\n10 thruster",
    "for time\r\n1500 mt run\r\n2-4-6-8-10-15-20 reps of\r\nbox jump\r\nhang power clean",
    "amrap 20 minutes\r\n7 deadlift\r\n7 burpee over the bar\r\n4 thruster\r\n3 shoulder to overhead\r\n100 mt run",
    "for time\r\n15-12-9 reps of\r\nclean & jerk\r\nburpee over the bar",
    "for time\r\n10 pull-up\r\n10 push-up\r\n10 clean & jerk",
    "3 rounds for time\r\n55 mt bear crawl\r\n30 sit-up\r\n10 burpee",
    "8 rounds for time\r\n21 clean & jerk\r\n15 double under",
    "20 rounds for time\r\n10 wall-ball\r\n12 double under",
    "for time\r\n15-15-15 reps of\r\nbench press\r\n12-9-6 reps of\r\nhang squat clean\r\nhandstand push-up",
    "3 rounds for time\r\n50 steps lunge\r\n30 push-up",
    "5 rounds for time\r\n500 mt row\r\n21 burpee",
    "4 rounds for time 15 minutes\r\n50 squats\r\n15 cal row\r\n15 pull-up\r\n6 sit-up",
    "5 rounds for time\r\n12 overhead squat\r\n400 mt run\r\n30 box jump",
    "6 rounds for time\r\n12 deadlift\r\n12 power clean\r\n25 push-up\r\ncash out: 75 double under",
    "amrap 12 minutes\r\n3 power snatch\r\n10 burpee over the barbell",
    "5 rounds for time\r\n20 double under\r\n10 pull-up\r\n15 thruster",
    "7 rounds for time\r\n10 dumbbell snatch\r\n10 toes to bar\r\ncash out: 400 mt run with a plate",
    "for time\r\ncash in: 1000 mt row\r\n21-15-9 reps of\r\npower clean\r\npull-up",
    "3 rounds for time\r\ncash in: 25 burpee\r\n400 mt run\r\n15 thruster",
    "for time 15 minutes\r\n3-6-9-12... reps of\r\nchest-to-bar pull-up\r\nkettlebell swing",
    "4 rounds for time\r\n200 mt sled pull\r\n15 thruster\r\n20 box jump over\r\n10 push jerk",
    "team of 2 complete for time\r\n1000 mt row\r\n50 burpee\r\n* everytime you break 100 mt dumbbell farmers carry",
    "2 rounds for time\r\n30 hand release push-up\r\n30 double under\r\n30 box jump\r\n20 kettlebell swing",
    "7 rounds for time\r\n3 rope climb\r\n10 toes to bar\r\n21 kettlebell swing",
    "5 rounds for time\r\n20 wall-ball\r\n12 power clean\r\n15 overhead squat\r\n15 sit-up",
    "for time\r\n21-18-15-12-9-6-3 reps of\r\nsumo deadlift high-pull\r\n* 30 double under after every round",
    "emom 20 minutes\r\n30 seconds l-sit hold\r\n30 seconds handstand hold",
    "for time\r\n25-20-15-10-5 reps of\r\nkettlebell swing\r\nbox jump",
    "amrap 18 minutes\r\n10 thruster\r\n10 box step-up\r\n10 toes to bar",
    "4 rounds\r\n500 mt row\r\nmax rep push press for 60 seconds\r\n800 mt run",
    "for time\r\n18-15-12-9-6-3 reps of\r\nhand release push-up\r\njumping lunge\r\nbox jump\r\n* 100 mt sprint after every round",
    "amrap 10 minutes\r\n5 thruster\r\n7 hang power clean\r\n10 sumo deadlift high-pull",
    "5 rounds\r\n20 cal row\r\n30 toes-to-bar",
    "5 rounds for time\r\n40 cal row\r\n40 air squat\r\n40 sit-up",
    "team of 2 complete 3 rounds for time\r\n40 ketllebell swing\r\n60 sit-up\r\n30 hang squat clean\r\n25 back extension\r\n30 wall-ball\r\n3 rope climb",
    "for time\r\n30-20-10 reps of\r\nsquat clean\r\nhand release push-up\r\n* 15 kettlebell swing after every round",
    "4 rounds\r\nmax rep wall-ball for 1 minute\r\nmax rep box jump for 1 minute\r\nmax rep dumbbell snatches for 1 minute\r\nmax rep burpee for 1 minute\r\nmax rep double under for 1 minute\r\n1 minute rest",
    "for time 30 minutes\r\n30 burpee over the bar\r\n30 kettlebell swing\r\n30 goblet squat\r\n30 pull-up",
    "for time 10 minutes\r\n20 shoulder to overhead\r\n40 back squat\r\n1000 mt row",
    "5 rounds for time\r\n12 deadlift\r\n12 hang power clean\r\n12 push press",
    "for time\r\n800 mt run\r\n25 overhead squat\r\n50 sit-up\r\n25 hang squat clean\r\n25 back extension\r\n30 wall-ball\r\n3 rope climb",
    "5 rounds for time\r\n400 mt run\r\n15 thruster",
    "4 rounds for time\r\n15 sumo deadlift high pull\r\n25 double under\r\n15 power snatch",
    "for time 15 minutes\r\n3-6-9-12... reps of\r\nwall-ball\r\n* 10 double under after every round",
    "emom 25 minutes\r\nmin 1: max rep hand release push-up\r\nmin 2: max rep v-up\r\nmin 3: max rep sit-up\r\nmin 4: max rep toes to bar\r\nmin 5: rest",
    "5 rounds for time\r\n50 mt barbell overhead walking lunge\r\n21 burpee",
    "every 5 minutes for 35 minutes\r\n250 mt row\r\n20 push-up\r\n20 sit-up",
    "amrap 15 minutes\r\n15 thruster\r\n12 burpee over the bar",
    "emom 12 minutes\r\nodd: 10 front squat\r\neven: 12 box jump over",
    "5 rounds for time\r\n5 muscle-up\r\n15 overhead squat",
    "amrap 10 minutes\r\n10 overhead squat\r\n12 sit-up\r\n21 double under",
    "for time\r\n50 box jump\r\n75 air squat\r\n40 cal row\r\n50 step-up with dumbbell",
    "amrap 20 minutes\r\n5 thruster\r\n7 hang power clean\r\n10 sumo deadlift high-pull",
    "for time\r\n15-12-9-6-3 reps of\r\npower clean\r\nburpee over the bar\r\nhand release push-up",
    "emom 20 minutes\r\nmin 1: max rep v-up\r\nmin 2: max rep box jump\r\nmin 3: max mt run\r\nmin 4: max rep dumbbell step-up with dumbbell\r\nmin 5: rest",
    "5 rounds for time\r\n10 dumbbell ground to overhead\r\n10 box jump over\r\n400 mt run\r\n10 burpee muscle-up",
    "10 rounds for time\r\n300 mt row\r\n20 air squat",
    "for time\r\n35-25-20-15-10 reps of\r\nkettlebell swing\r\nhand release push-up",
    "for time\r\n50 box jump\r\n50 jumping pull-up\r\n50 kettlebell swing\r\n50 steps walking lunge\r\n50 knees to elbow\r\n50 push press\r\n50 back extension\r\n50 wall-ball\r\n50 burpee\r\n50 double under",
    "for time\r\n50-40-30-20-10 reps of\r\ndouble under\r\nsit-up",
    "for time\r\n30 handstand push-up\r\n40 pull-up\r\n50 kettlebell swing\r\n60 sit-up\r\n90 burpee",
    "5 rounds for time\r\n10 pull-up\r\n30 sit-up\r\n10 hang power snatch",
    "3 rounds for time\r\n20 burpee\r\n20 toes to bar\r\n10 thruster",
    "5 rounds for time\r\n250 mt row\r\n12 hang power clean\r\n12 hand release push-up",
    "amrap 25 minutes\r\n3-6-9-12... reps of\r\npush-up\r\ntoes-to-bar\r\nwall-ball",
    "3 rounds for time\r\n800 mt run\r\n50 back extension\r\n50 sit-up",
    "for time\r\n21-15-9 reps of\r\ndeadlift\r\nhandstand push-up\r\ncash out: 100 double under",
    "amrap 20 minutes\r\n10 hang power clean\r\n10 goblet squat",
    "4 rounds\r\n15 cal row\r\n30 double under\r\n15 goblet squat",
    "every 5 minutes for 30 minutes (5 rounds)\r\n800 mt run\r\n21 dumbbell thruster",
    "emom 12 minutes\r\nodd: 8 power snatch\r\neven: 12 push jerk",
    "emom 21 minutes\r\nmin 1: max rep chin-up\r\nmin 2: max rep sit-up\r\nmin 3: max rep toes-to-bar",
    "team of 2 complete amrap 14 minutes\r\n30 double under\r\n12 burpee\r\n12 box jump\r\n9 toes-to-bar",
    "for time\r\n100 double under\r\n50 thruster\r\n25 pull-up",
    "5 rounds for time\r\n7 muscle-up\r\n11 rope climb",
    "for time\r\n40 dumbbell snatch\r\n400 mt run\r\n20 pull-up\r\n400 mt run\r\n20 left arm snatch\r\n20 right arm snatch\r\n20 pull-up\r\n400 mt run",
    "2 rounds for time\r\ncash in: 1500 mt run\r\n20 pull-up\r\n30 sit-up\r\n40 burpee",
    "amrap 24 minutes\r\n200 mt run\r\n10 thruster\r\n15 pull-up",
    "team of 2 complete amrap 20 minutes\r\n50 burpee box jump over\r\n30 back squat",
    "emom 12 minutes\r\nmin 1: max rep hand release push-up\r\nmin 2: max rep wall-ball\r\nmin 3: max rep toes to bar\r\nmin 4: rest",
    "amrap 10 minutes\r\n10 hand release push-up\r\n10 double under\r\n10 wall-ball",
    "10 rounds for time\r\n1 rope climb\r\n15 ring dip\r\n15 triple under",
    "for time\r\n21-15-9 reps of\r\noverhead squat\r\nfront squat\r\n* 10 double under after every round",
    "3 rounds for time\r\n500 mt row\r\n21 burpee\r\n27 kettlebell swing",
    "amrap 12 minutes\r\n3 thruster\r\n3 burpee\r\n2 minutes rest\r\namrap 8 minutes\r\n3 squat clean\r\n5 push-up",
    "7 rounds for time\r\n7 thrusters\r\n7 burpee\r\n7 pull-up\r\n* 400 mt run after every round",
    "for time\r\n21-18-15-12-9-6-3 reps of\r\nkettlebell swing\r\nbox jump\r\nthruster",
    "amrap 20 minutes\r\n10 deadlift\r\n8 hang power clean\r\n6 push jerk",
    "team of 2 complete amrap 20 minutes\r\n500 mt row\r\n30 kettlebell swing\r\n10 thruster\r\n10 burpee over bar",
    "emom 30 minutes\r\nmin 1: 5 deadlift\r\nmin 2: 8 hang power snatch\r\nmin 3: 30 double under\r\nmin 4: 15 kettlebell swing\r\nmin 5: rest",
    "team of 2 complete amrap 20 minutes\r\n600 mt row\r\n40 kettlebell swing\r\n20 thruster\r\n20 chest-to-bar pull-up\r\n20 overhead squat\r\n20 toes-to-bar\r\n30 wall-ball",
    "3 rounds for time\r\n400 mt run\r\n30 box jump\r\n30 wall-ball",
    "amrap 15 minutes\r\n10 kettlebell swing\r\n10 box jump-over\r\n30 dumbbell clean & jerk",
    "for time\r\n30 cal row\r\n50 wall-ball\r\n30 box jump\r\n20 pull-up",
    "for time 16 minutes\r\n2-4-6-8... reps of\r\npower snatch\r\nburpee over the bar",
    "emom 30 minutes\r\nmin 1: max rep power clean\r\nmin 2: max rep double under\r\nmin 3: max rep dip\r\nmin 4: max rep ring row\r\nmin 5: rest",
    "5 rounds for time\r\n25 one-legged squat\r\n25 pull-up",
    "5 rounds for time 25 minutes\r\n400 mt run\r\n15 overhead squat"
  ];
}
